print("""
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMWX0kdlc::;;;;;::cloddk0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMWKxl;'..';:cloooooollc:,''.';lx0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMXl,:lxOXNWMMMMMMMMMMMMMWNX0xo:'.';lx0XWMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMWNNWMMMMMMMMMMMMMMMMMMMMMMMMMWN0xl:,,,;clloddxxONMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMNKOdolllllodk0XNMMMMMMMMMMMWNX0OxdoolllldXMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMWXd;'.         .';:clokKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMWk;,od'         .dX0xdl;';ok0XNNWWWWMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMWKl,lKMX:         'OMMWWXo.  .'',;;:::ccccllllkNMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMKo..cO0KKk,       .cxdolc::lxO000OOOkkkkxxddollkNMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMWkc:ccc,....     .,:llox0KXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWo   .:,   ;ONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWd.  ;KNkc. .:kNMMMMMMMMMMMMMMMMMMMMMXOOk0NMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMM0,   :XMMWKx:..'oONWMMMMMMMMMMMMMMMMXddxdodXMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMK,   dWMMMMMWXxc'.,:lkXWMMMMMMMMMMMMNkddxOdOMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMk. .kMMMMMMMMMMNOoc;',:dOXWMMMMMMMMMWXKKxdKMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMXc .OMMMMMMMMMMMMMMWXko:,;:lxOKXNNNX0kxoxKMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMk.'0MMMMMMMMMMMMMMMMMMWN0xolcclloooodkXWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMNOONMMMMMMMMMMMMMMMMMMMMMMMMWWNNNWWMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
""")